### ISSUE TITLE
Set-up ci with github 

### ISSUE THREAD

**Issue by jasonodoom** [rubyforgood/stocks-in-the-future#10]

**Comment by malsmr** [comment]
I would like to help with this. Please let me know if its ready to be picked up?

**Comment by garettarrowood** [comment]
@malsmr - This project will be ready for OS contributions very soon but not quite yet. A lot of us are at Ruby for Good event this weekend organizing and planning, so things are changing fast. Check back in another day or so, and if there is not an assignee on an issue, we'll welcome your help!

This issue specifically is already getting worked on. If an issue has an assignee already, it's likely unavailable.

**Comment by jasonodoom** [comment]
This is done. There will be some improvements ofc but CD is next on the list
