### ISSUE TITLE
Create school and cohort models

### ISSUE THREAD

**Issue by LizPrescott** [rubyforgood/stocks-in-the-future#13]
### School 
Id 
Name

### Cohort
Id
name: txt, null: false
school_id, null: false
school_year_id: int
grade: int, null: false
teacher_id: int, null: false
active: boolean, default: true

cohorts have a many to one relationship with schools

**Comment by malsmr** [comment]
I would like to help with this. Please let me know if its ready to be picked up?

**Comment by randallreedjr** [comment]
Since cohort references school_year, I am going to go ahead and create school_year model here, instead of as part of #15
