### ISSUE TITLE
Add a Test Admin Page for Adding Money to Student Account

### ISSUE THREAD

**Issue by JAYKAY2291** [rubyforgood/stocks-in-the-future#142]
# Summary

Test Admin page is need for adding money to student account. This is needed for testing functionality of "adding money."

## Things out of Scope
Do not add separate student account as that is a separate issue. Do not fix small mistakes/problem that might be found in admin; this can be done separately, as long as page is functional these do not need to be dealt with at the moment.

# Criteria for Completion
 - [x] Admin user should be able to add funds to a student account and see that it was sent.
 - [x] This feature should only be available to admins
 - [x] Add automated test to ensure functionality

**Comment by h-m-m** [comment]
This looks done to me
