### ISSUE TITLE
Add function that will pull API and Implement API changes at EOD.

### ISSUE THREAD

**Issue by JAYKAY2291** [rubyforgood/stocks-in-the-future#146]
# Summary

Function needed that will pull API at the end of each day and implement price changes.

## Things out of Scope
This function is independent of adding buy orders which is called out in issue #145, although this function will be working in tandem with the buy order function. 

# Criteria for Completion
> This should be a bulleted list of items that, if satisfied, would result in an acceptably complete Pull Request. Be as specific as you need to be. For example:

 - [x] At the end of each day, API should be pulled, and displayed stock prices should be changed. 
 - [x] This feature must be available for all users to view.
 - [x] Add a test proving that it works

**Comment by abachman** [comment]
related issue in #56
