### ISSUE TITLE
Add role to User model

### ISSUE THREAD

**Issue by suttondemlong** [rubyforgood/stocks-in-the-future#28]
--------

# Summary

Users need to have a "role" that can be used for permissions. These roles will be: admin, teacher, student, alumni. Users may have more than one role. 

## Things to Consider
> Once everything is set up these roles will be used to decide permissions granted to users. Probably a student cannot be an alumni at the same time, however a teacher might be able to be an admin.

# Criteria for Completion

 - [x] role has been added to user model
 - [x] role is an enum array
 - [x] role cannot be anything but ADMIN, TEACHER, STUDENT, ALUMNI
 - [x] appropriate tests have been written

-------

**Comment by naomiyocum** [comment]
I can work on this!
