### ISSUE TITLE
Setup CD with Github

### ISSUE THREAD

**Issue by jasonodoom** [rubyforgood/stocks-in-the-future#38]
CD would be great to have in order to release and test quickly.

**Comment by jasonodoom** [comment]
> Note that to do this, we will need to get hosting sorted.

I was thinking of trying this with GH Pages. Not sure what the restrictions are but could work.

**Comment by garettarrowood** [comment]
We have all the CD we need for the time being. Repo is deploying to https://stocks-in-the-future-2e5bd264d30e.herokuapp.com/ with merges to `main`.
