### ISSUE TITLE
Updates to main README

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/stocks-in-the-future#45]
# Summary

The main README could use a few things. 
1. A description of Stocks In The Future with a link to their external static site - https://sifonline.org/
2. A Ruby for Good welcome message with instructions on joining their slack and going to our #stocks-in-the-future channel
3. Reference to our deployment of this repo at https://stocks-in-the-future-2e5bd264d30e.herokuapp.com/

# Criteria for Completion
 - [ ] README is updated with criteria
 - [ ] Good spelling and grammar - anticipate some discussion on wording.

**Comment by iallah1** [comment]
Hi there! I'm going to go ahead and try to work on this
