### ISSUE TITLE
Refactor & Integrate EOD Stock updates into Stock Ticker

### ISSUE THREAD

**Issue by garettarrowood** [rubyforgood/stocks-in-the-future#56]
# Summary

The initial work to select and integrate a Stock API has been accomplished. We will be using [MarketStack](https://marketstack.com/), which provides 1,000 free stock price updates a month under a free plan. If our stakeholder wants more updates, we can talk to her about purchasing a paid plan.

The initial implementation isn't lengthy, but/and needs some re-architecting.

This issue can be completed in stages (multiple PRs) or all together. You may want to go create a free MarketStack account for yourself. It does not require you enter any financial info. 

See criteria.

## Things to Consider

#32 
#37 
#55 

# Criteria for Completion

- [ ] Move values into config instead leaving as constants in api files.
- [ ] Use Redis cache wrappers, [as mentioned here](https://github.com/rubyforgood/stocks-in-the-future/pull/37#discussion_r1280592493)
- [ ] Leverage ActiveModel, [as mentioned here](https://github.com/rubyforgood/stocks-in-the-future/pull/37#discussion_r1280595107)
- [ ] Consider using `Faraday` instead of `Net::HTTP`, [as mentioned here](https://github.com/rubyforgood/stocks-in-the-future/pull/32#discussion_r1278585113)
- [ ] More refactoring. [Here's one relevant comment](https://github.com/rubyforgood/stocks-in-the-future/pull/32#discussion_r1278585453). Personally, I don't think any of this should be in `models/`, and may be better namespaced in an `app/api/` directory where the classes are `Api::Stock`/etc.
- [ ] Rewire #37 to use updated logic once the above bullets have been addressed.
- [ ] As a result of rewiring #37 , the Stock Ticker will be functional and update daily.

**Comment by malsmr** [comment]
Is this ready to be worked on?

**Comment by garettarrowood** [comment]
@malsmr - Absolutely! - Please feel free to do some of the bullets and document any constraints concerns in regards to obtaining any others. Accomplishing this in multiple deliverables is fine by me.

**Comment by h-m-m** [comment]
We've gone with a different API and are generally breaking this work up into smaller issues
